import { Stage } from "./types";

const SISTEMAS_OPTIONS = [
  { value: "crm", label: "CRM" },
  { value: "erp", label: "ERP" },
  { value: "portal-web", label: "Portal Web" },
  { value: "app-movil", label: "App Móvil" },
  { value: "core", label: "Core Transaccional" },
  { value: "dwh", label: "Data Warehouse" },
  { value: "otro", label: "Otro" },
];

/**
 * Las 6 etapas macro del portafolio, una por cada archivo de flujo homologado
 * "To Be" (Flujo 0 a Flujo 5). Cada `substep` reconstruye fielmente los pasos,
 * decisiones y responsables descritos en esos documentos.
 */
export const stages: Stage[] = [
  {
    id: "priorizacion",
    order: 0,
    key: "flujo-0",
    name: "Priorización",
    shortName: "Priorización",
    sourceFlow: "Flujo 0 - Flujo de Priorización To Be",
    description:
      "Descubrimiento y priorización de la idea: desde la solicitud del área de negocio hasta la entrega del Canvas a Arquitectura.",
    lanes: ["Director de Negocio", "PMO", "BP's", "Líder de Arquitectura"],
    color: "#579BFC",
    substeps: [
      {
        id: "p-01",
        order: 1,
        title: "Solicitud de requerimiento",
        description:
          "El área de negocio solicita un nuevo requerimiento para iniciar el proceso.",
        responsibleLane: "Director de Negocio",
        type: "task",
        formFields: [
          { id: "titulo", label: "Título de la iniciativa", type: "text", required: true },
          { id: "areaSolicitante", label: "Área solicitante", type: "text", required: true },
          { id: "descripcion", label: "Descripción del requerimiento", type: "textarea" },
        ],
      },
      {
        id: "p-02",
        order: 2,
        title: "Visualizar backlog por cartera de negocio",
        description: "La PMO revisa los requerimientos pendientes en el backlog.",
        responsibleLane: "PMO",
        type: "task",
      },
      {
        id: "p-03",
        order: 3,
        title: "Perfilamiento de la idea",
        description:
          "Se analiza y define la idea inicial. Decisión: ¿el proyecto es de TI?",
        responsibleLane: "PMO",
        type: "decision",
        branches: [
          { label: "NO", text: "Sigue el flujo de proyectos no tecnológicos (fuera de alcance de este sistema)." },
          { label: "SI", text: "Continúa como proyecto de TI.", targetSubStepId: "p-04" },
        ],
      },
      {
        id: "p-04",
        order: 4,
        title: "Realizar priorización",
        description: "La PMO prioriza la iniciativa frente a otras del portafolio.",
        responsibleLane: "PMO",
        type: "task",
        formFields: [
          {
            id: "prioridad", label: "Prioridad", type: "select", required: true,
            options: [{ value: "alta", label: "Alta" }, { value: "media", label: "Media" }, { value: "baja", label: "Baja" }],
          },
          { id: "carteraNegocio", label: "Cartera de negocio", type: "text" },
          { id: "justificacion", label: "Justificación de la priorización", type: "textarea" },
        ],
      },
      {
        id: "p-05",
        order: 5,
        title: "Formalizar backlog y notificar",
        description: "Se formaliza la priorización en el backlog y se notifica a las áreas correspondientes.",
        responsibleLane: "PMO",
        type: "task",
      },
      {
        id: "p-06",
        order: 6,
        title: "Realizar Canvas de la idea",
        description: "El Director de Negocio elabora el Canvas, detallando la idea, el equipo necesario, etc.",
        responsibleLane: "Director de Negocio",
        type: "task",
        formFields: [
          { id: "objetivo", label: "Objetivo de la iniciativa", type: "textarea", required: true },
          { id: "problema", label: "Problema a resolver", type: "textarea", required: true },
          {
            id: "equipoRequerido", label: "Equipo requerido", type: "multiselect",
            options: [
              { value: "lider-arquitectura", label: "Líder de Arquitectura" },
              { value: "lideres-tecnicos", label: "Líderes Técnicos" },
              { value: "bp", label: "Business Partner" },
              { value: "equipo-tecnico", label: "Equipo Técnico" },
            ],
          },
          { id: "beneficiosEsperados", label: "Beneficios esperados", type: "textarea" },
          { id: "alcance", label: "Alcance", type: "textarea" },
          { id: "riesgosIniciales", label: "Riesgos iniciales", type: "textarea" },
        ],
      },
      {
        id: "p-07",
        order: 7,
        title: "Revisión de calidad de información del Canvas",
        description: "Los Business Partners revisan que la información del Canvas sea de calidad. Decisión: ¿la información es completa?",
        responsibleLane: "BP's",
        type: "approval",
        approverRoleId: "bp",
        branches: [
          { label: "NO", text: "Se notifica al Director de Negocio para ajustar/corregir.", targetSubStepId: "p-08" },
          { label: "SI", text: "La información es completa, el proceso continúa.", targetSubStepId: "p-09" },
        ],
      },
      {
        id: "p-08",
        order: 8,
        title: "Ajustar / Corregir Canvas",
        description: "El Director de Negocio corrige o ajusta la información del Canvas y lo reenvía a revisión.",
        responsibleLane: "Director de Negocio",
        type: "task",
      },
      {
        id: "p-09",
        order: 9,
        title: "Complementar contexto de iniciativa",
        description: "Los BP's añaden contexto adicional a la iniciativa. Decisión: ¿la información está completa ahora?",
        responsibleLane: "BP's",
        type: "approval",
        approverRoleId: "bp",
        branches: [
          { label: "NO", text: "Se sigue complementando el contexto.", targetSubStepId: "p-09" },
          { label: "SI", text: "El proceso avanza.", targetSubStepId: "p-10" },
        ],
      },
      {
        id: "p-10",
        order: 10,
        title: "Entrega de versión final de Canvas a Negocio y Arquitectura",
        description: "Los BP's entregan el documento finalizado.",
        responsibleLane: "BP's",
        type: "task",
      },
      {
        id: "p-11",
        order: 11,
        title: "Recepción de Canvas y asignación de líder de arquitectura de Dominio",
        description: "El área de Arquitectura recibe el Canvas y asigna un líder para el dominio correspondiente.",
        responsibleLane: "Líder de Arquitectura",
        type: "task",
        formFields: [
          { id: "arquitectoAsignado", label: "Arquitecto de dominio asignado", type: "select" },
          { id: "comentarios", label: "Comentarios de recepción", type: "textarea" },
        ],
      },
    ],
  },

  {
    id: "estimacion-preliminar",
    order: 1,
    key: "flujo-1",
    name: "Estimación Preliminar",
    shortName: "Estimación",
    sourceFlow: "Flujo 1 - Flujo Homologado To Be - Estimación Preliminar",
    description:
      "Análisis técnico, generación de la estimación (AsisTI) y validación con Arquitectura, Líderes Técnicos, Negocio y BP.",
    lanes: ["Líder Arquitectura", "AsisTI", "Líderes Técnicos", "BP"],
    color: "#A25DDC",
    substeps: [
      {
        id: "e-01",
        order: 1,
        title: "Realizar análisis preliminar",
        description: "Análisis de alto nivel de los sistemas que serán impactados.",
        responsibleLane: "Líder Arquitectura",
        type: "task",
        formFields: [
          { id: "sistemasImpactados", label: "Sistemas impactados", type: "multiselect", options: SISTEMAS_OPTIONS },
          {
            id: "complejidad", label: "Complejidad estimada", type: "select",
            options: [{ value: "baja", label: "Baja" }, { value: "media", label: "Media" }, { value: "alta", label: "Alta" }],
          },
        ],
      },
      {
        id: "e-02",
        order: 2,
        title: "Generar estimación (AsisTI DataSwat)",
        description: "Se genera una estimación inicial con la herramienta AsisTI DataSwat, resguardando posibles alternativas.",
        responsibleLane: "AsisTI",
        type: "task",
        formFields: [
          { id: "horasInfraestructura", label: "Horas Infraestructura", type: "number" },
          { id: "horasDesarrollo", label: "Horas Desarrollo", type: "number" },
          { id: "horasUX", label: "Horas UX", type: "number" },
          { id: "horasQA", label: "Horas QA", type: "number" },
          { id: "alternativas", label: "Alternativas consideradas", type: "textarea" },
          { id: "costoEstimado", label: "Costo estimado", type: "currency" },
        ],
      },
      {
        id: "e-03",
        order: 3,
        title: "Enviar estimación para Visto Bueno (Vo.Bo.)",
        description: "La estimación se envía para aprobación del Líder de Arquitectura y los Líderes Técnicos de dominio; se confirma el acuse de recibo.",
        responsibleLane: "AsisTI",
        type: "task",
      },
      {
        id: "e-04",
        order: 4,
        title: "¿Se otorga el Vo.Bo. de la estimación? (Arquitectura)",
        description: "El Líder de Arquitectura decide si otorga el visto bueno de la estimación.",
        responsibleLane: "Líder Arquitectura",
        type: "approval",
        approverRoleId: "lider-arquitectura",
        branches: [
          { label: "NO", text: "Se regresa a definir estimación para realizar ajustes.", targetSubStepId: "e-02" },
          { label: "SI", text: "El flujo continúa.", targetSubStepId: "e-05" },
        ],
      },
      {
        id: "e-05",
        order: 5,
        title: "¿Se otorga el Vo.Bo. de la estimación? (Líderes Técnicos)",
        description: "Los Líderes Técnicos deciden si otorgan el visto bueno de la estimación.",
        responsibleLane: "Líderes Técnicos",
        type: "approval",
        approverRoleId: "lideres-tecnicos",
        branches: [
          { label: "NO", text: "Se regresa a definir estimación para realizar ajustes.", targetSubStepId: "e-02" },
          { label: "SI", text: "El flujo continúa.", targetSubStepId: "e-06" },
        ],
      },
      {
        id: "e-06",
        order: 6,
        title: "Vo.Bo. del Director de Negocio",
        description: "Una vez aprobada técnicamente, la estimación se envía al Director de Negocio para su visto bueno.",
        responsibleLane: "AsisTI",
        type: "approval",
        approverRoleId: "director-negocio",
        branches: [
          { label: "NO", text: "Se regresa a definir estimación para realizar ajustes.", targetSubStepId: "e-02" },
          { label: "SI", text: "El flujo continúa.", targetSubStepId: "e-07" },
        ],
      },
      {
        id: "e-07",
        order: 7,
        title: "Entregar estimación preliminar y hoja de costo a BP",
        description: "Se formaliza la entrega de los documentos al BP.",
        responsibleLane: "AsisTI",
        type: "task",
        formFields: [{ id: "notasEntrega", label: "Notas de entrega", type: "textarea" }],
      },
      {
        id: "e-08",
        order: 8,
        title: "Recepción y Vo.Bo. de la estimación preliminar",
        description: "El BP recibe la estimación (vía Gmail AsisTI) y da su visto bueno final.",
        responsibleLane: "BP",
        type: "approval",
        approverRoleId: "bp",
        branches: [
          { label: "NO", text: "Se regresa a definir estimación para realizar ajustes.", targetSubStepId: "e-02" },
          { label: "SI", text: "El flujo continúa.", targetSubStepId: "e-09" },
        ],
      },
      {
        id: "e-09",
        order: 9,
        title: "Enviar Minuta Automática y Publicar Status Global",
        description: "Se notifica a todos los interesados sobre la aprobación y el estado de la iniciativa.",
        responsibleLane: "AsisTI",
        type: "task",
      },
      {
        id: "e-10",
        order: 10,
        title: "Presentar iniciativa a la Dirección de Negocio",
        description: "El BP presenta formalmente la iniciativa a la dirección para su aprobación final y asignación de recursos.",
        responsibleLane: "BP",
        type: "task",
        formFields: [
          { id: "fechaPresentacion", label: "Fecha de presentación", type: "date" },
          {
            id: "resultado", label: "Resultado", type: "select",
            options: [{ value: "aprobado", label: "Aprobado" }, { value: "pendiente", label: "Pendiente" }],
          },
        ],
      },
    ],
  },

  {
    id: "autorizacion",
    order: 2,
    key: "flujo-2",
    name: "Autorización",
    shortName: "Autorización",
    sourceFlow: "Flujo 2 - Flujo Homologado To Be - Autorización",
    description:
      "Aprobación del caso de negocio con Dirección General, formalización en Charter y solicitud del PEP.",
    lanes: ["Director de Negocio - PMOs", "Portafolio / SE / Serv. Est.", "Finanzas TI / SE Finanzas"],
    color: "#FDAB3D",
    substeps: [
      {
        id: "a-01",
        order: 1,
        title: "Presentar Caso de Negocio y Aprobar con DG",
        description: "Se presenta la iniciativa a la Dirección General para obtener su aprobación.",
        responsibleLane: "Director de Negocio - PMOs",
        type: "approval",
        approverRoleId: "direccion-general",
        formFields: [
          { id: "resumenEjecutivo", label: "Resumen ejecutivo", type: "textarea" },
          { id: "roiEstimado", label: "ROI estimado (%)", type: "number" },
          { id: "montoSolicitado", label: "Monto solicitado", type: "currency" },
        ],
        branches: [
          { label: "NO", text: "La idea se archiva en el backlog.", targetSubStepId: "a-02" },
          { label: "SI", text: "El proceso continúa.", targetSubStepId: "a-03" },
        ],
      },
      {
        id: "a-02",
        order: 2,
        title: "Guardar idea en Backlog",
        description: "La iniciativa queda registrada en el backlog y el flujo finaliza para esta propuesta.",
        responsibleLane: "Director de Negocio - PMOs",
        type: "task",
      },
      {
        id: "a-03",
        order: 3,
        title: "Notificar la aprobación",
        description: "Se comunica la aprobación a los equipos correspondientes.",
        responsibleLane: "Director de Negocio - PMOs",
        type: "task",
      },
      {
        id: "a-04",
        order: 4,
        title: "Formalización en Charter",
        description: "Se formaliza la iniciativa en un documento Charter, utilizando una herramienta de digitalización.",
        responsibleLane: "Director de Negocio - PMOs",
        type: "task",
        formFields: [
          { id: "folioCharter", label: "Folio del Charter", type: "text" },
          { id: "fechaFormalizacion", label: "Fecha de formalización", type: "date" },
          { id: "documentoAdjunto", label: "Documento Charter", type: "file" },
        ],
      },
      {
        id: "a-05",
        order: 5,
        title: "Mandar Charter a Firma",
        description: "El Charter se envía para recabar las firmas necesarias.",
        responsibleLane: "Portafolio / SE / Serv. Est.",
        type: "task",
        formFields: [
          {
            id: "firmantes", label: "Circuito de firmantes", type: "table",
            columns: [
              { id: "nombre", label: "Nombre", type: "text" },
              { id: "rol", label: "Rol", type: "text" },
              { id: "status", label: "Status", type: "select" },
            ],
          },
        ],
      },
      {
        id: "a-06",
        order: 6,
        title: "Seguimiento automatizado del circuito de firmas",
        description: "Se realiza un seguimiento automático del proceso de autorización del Charter.",
        responsibleLane: "Portafolio / SE / Serv. Est.",
        type: "task",
      },
      {
        id: "a-07",
        order: 7,
        title: "Solicitud de PEP",
        description: "Una vez autorizado, se solicita un Elemento PEP (Proyecto Estructural de Presupuesto), activando el control financiero.",
        responsibleLane: "Portafolio / SE / Serv. Est.",
        type: "task",
        formFields: [{ id: "montoPresupuestado", label: "Monto presupuestado (PEP)", type: "currency" }],
      },
      {
        id: "a-08",
        order: 8,
        title: "Envío automatizado de la solicitud de creación y asignación del PEP",
        description: "La solicitud se envía de forma automática para su procesamiento.",
        responsibleLane: "Portafolio / SE / Serv. Est.",
        type: "task",
      },
      {
        id: "a-09",
        order: 9,
        title: "Revisión de costos",
        description: "El equipo de finanzas revisa los costos asociados a la iniciativa.",
        responsibleLane: "Finanzas TI / SE Finanzas",
        type: "approval",
        approverRoleId: "director-finanzas",
        branches: [
          { label: "NO", text: "Se regresa a la solicitud de PEP para ajustar montos.", targetSubStepId: "a-07" },
          { label: "SI", text: "Se generan los vistos buenos.", targetSubStepId: "a-10" },
        ],
      },
      {
        id: "a-10",
        order: 10,
        title: "Generación y notificación automática de Vistos Buenos (VoBos)",
        description: "Se generan y notifican automáticamente los vistos buenos necesarios para continuar.",
        responsibleLane: "Finanzas TI / SE Finanzas",
        type: "task",
      },
      {
        id: "a-11",
        order: 11,
        title: "Formalización de asignación y entrega",
        description: "Se oficializa la asignación del proyecto y se entrega a los equipos responsables para su ejecución.",
        responsibleLane: "Portafolio / SE / Serv. Est.",
        type: "task",
      },
    ],
  },

  {
    id: "formalizacion-autorizacion",
    order: 3,
    key: "flujo-3",
    name: "Formalización y Autorización",
    shortName: "Formalización",
    sourceFlow: "Flujo 3 - Flujo Homologado To Be - Formalización y Autorización",
    description:
      "Ruta doble: formalización de la asignación del proyecto y, en paralelo, arranque de la gestión de proveedores/contratos.",
    lanes: ["Director de Negocio / PMOs", "Portafolio / SE / Serv. Est.", "Finanzas TI / SE Finanzas", "Equipo Técnico / PMO"],
    color: "#E10098",
    substeps: [
      {
        id: "fa-01",
        order: 1,
        title: "Presentar Caso de Negocio y Aprobar con DG",
        description: "El proceso arranca con la presentación del caso de negocio a la Dirección General para su aprobación.",
        responsibleLane: "Director de Negocio / PMOs",
        type: "approval",
        approverRoleId: "direccion-general",
        branches: [
          { label: "NO", text: "La iniciativa se archiva.", targetSubStepId: "fa-02" },
          { label: "SI", text: "El proceso avanza.", targetSubStepId: "fa-03" },
        ],
      },
      {
        id: "fa-02",
        order: 2,
        title: "Guardar idea en Backlog",
        description: "La idea queda registrada y el flujo termina para esta propuesta.",
        responsibleLane: "Director de Negocio / PMOs",
        type: "task",
      },
      {
        id: "fa-03",
        order: 3,
        title: "Notificar la aprobación",
        description: "Se notifica a las áreas involucradas sobre la decisión.",
        responsibleLane: "Director de Negocio / PMOs",
        type: "task",
      },
      {
        id: "fa-04",
        order: 4,
        title: "Formalización en Charter",
        description: "Se procede a digitalizar y formalizar la iniciativa en un documento Charter.",
        responsibleLane: "Director de Negocio / PMOs",
        type: "task",
        formFields: [
          { id: "folioCharter", label: "Folio del Charter", type: "text" },
          { id: "fechaFormalizacion", label: "Fecha de formalización", type: "date" },
        ],
      },
      {
        id: "fa-05",
        order: 5,
        title: "Mandar Charter a Firma",
        description: "El Charter se distribuye para obtener las firmas de autorización necesarias.",
        responsibleLane: "Portafolio / SE / Serv. Est.",
        type: "task",
      },
      {
        id: "fa-06",
        order: 6,
        title: "Seguimiento automatizado del circuito de firmas",
        description: "Se monitorea de forma automática el avance del proceso de firmas del Charter.",
        responsibleLane: "Portafolio / SE / Serv. Est.",
        type: "task",
      },
      {
        id: "fa-07",
        order: 7,
        title: "Solicitud de PEP",
        description: "Una vez firmado, se solicita la creación de un Elemento PEP, disparando el flujo de control financiero.",
        responsibleLane: "Portafolio / SE / Serv. Est.",
        type: "task",
        formFields: [{ id: "montoPresupuestado", label: "Monto presupuestado (PEP)", type: "currency" }],
      },
      {
        id: "fa-08",
        order: 8,
        title: "Envío automatizado de la solicitud de PEP",
        description: "La solicitud para la creación y asignación del PEP se envía automáticamente.",
        responsibleLane: "Portafolio / SE / Serv. Est.",
        type: "task",
      },
      {
        id: "fa-09",
        order: 9,
        title: "Revisión de costos",
        description: "El área de Finanzas realiza una revisión detallada de los costos asociados.",
        responsibleLane: "Finanzas TI / SE Finanzas",
        type: "approval",
        approverRoleId: "director-finanzas",
        branches: [
          { label: "NO", text: "Se regresa a la solicitud de PEP para ajustar montos.", targetSubStepId: "fa-07" },
          { label: "SI", text: "Se emiten los vistos buenos financieros.", targetSubStepId: "fa-10" },
        ],
      },
      {
        id: "fa-10",
        order: 10,
        title: "Generación y notificación automática de Vistos Buenos (VoBos)",
        description: "Se emiten y notifican los vistos buenos financieros, requisito para la formalización final.",
        responsibleLane: "Finanzas TI / SE Finanzas",
        type: "task",
      },
      {
        id: "fa-11",
        order: 11,
        title: "Formalización de asignación y entrega",
        description:
          "Con las autorizaciones y el PEP listos, se formaliza la asignación del proyecto y se entrega al equipo técnico. Rama A: termina aquí.",
        responsibleLane: "Portafolio / SE / Serv. Est.",
        type: "task",
      },
      {
        id: "fa-12",
        order: 12,
        title: "Solicitud y gestión de proveedores",
        description: "Rama B (en paralelo): tras recibir el proyecto, el equipo técnico inicia la gestión de proveedores o contratos necesarios.",
        responsibleLane: "Equipo Técnico / PMO",
        type: "task",
        formFields: [
          {
            id: "proveedores", label: "Proveedores / contratos", type: "table",
            columns: [
              { id: "proveedor", label: "Proveedor", type: "text" },
              { id: "contrato", label: "Contrato", type: "text" },
              { id: "status", label: "Status", type: "select" },
            ],
          },
        ],
      },
      {
        id: "fa-13",
        order: 13,
        title: "Gestión automatizada de proveedores y formalización de contratos",
        description: "Se gestiona la relación con proveedores y la formalización de contratos de manera automatizada. Rama B: termina aquí.",
        responsibleLane: "Equipo Técnico / PMO",
        type: "approval",
        approverRoleId: "equipo-tecnico",
      },
    ],
  },

  {
    id: "proyecto",
    order: 4,
    key: "flujo-4",
    name: "Proyecto (Ejecución)",
    shortName: "Ejecución",
    sourceFlow: "Flujo 4 - Flujo Homologado To Be - Proyecto",
    description:
      "Ejecución, control de cambios, cierre de hitos y proceso financiero en paralelo (órdenes de compra/servicio).",
    lanes: ["PMOs", "Líder Técnico / Serv. Infra.", "Portafolio / SE / Serv. Est.", "Finanzas TI / Compras"],
    color: "#00C875",
    substeps: [
      {
        id: "pr-01",
        order: 1,
        title: "Notificar Plan de Trabajo",
        description: "La PMO notifica el plan de trabajo a todos los equipos involucrados.",
        responsibleLane: "PMOs",
        type: "task",
        formFields: [
          { id: "planAdjunto", label: "Plan de trabajo", type: "file" },
          {
            id: "metodologia", label: "Metodología", type: "select",
            options: [{ value: "cascada", label: "Cascada (Monday)" }, { value: "agil", label: "Ágil (Jira)" }],
          },
        ],
      },
      {
        id: "pr-02",
        order: 2,
        title: "Inicio Desarrollo",
        description: "El equipo técnico da comienzo a las tareas de desarrollo.",
        responsibleLane: "Líder Técnico / Serv. Infra.",
        type: "task",
        formFields: [{ id: "avancePorcentaje", label: "Avance (%)", type: "number" }],
      },
      {
        id: "pr-03",
        order: 3,
        title: "Validación de Entregables y Solicitud de Liberación",
        description: "Se validan los entregables desarrollados y se solicita su liberación.",
        responsibleLane: "Líder Técnico / Serv. Infra.",
        type: "approval",
        approverRoleId: "lideres-tecnicos",
        formFields: [
          {
            id: "entregables", label: "Entregables", type: "table",
            columns: [{ id: "nombre", label: "Entregable", type: "text" }, { id: "status", label: "Status", type: "select" }],
          },
        ],
        branches: [
          { label: "NO", text: "Se regresa a desarrollo para atender observaciones.", targetSubStepId: "pr-02" },
          { label: "SI", text: "Se libera y continúa el monitoreo.", targetSubStepId: "pr-04" },
        ],
      },
      {
        id: "pr-04",
        order: 4,
        title: "Ejecución, Monitoreo y Control",
        description: "La PMO supervisa la ejecución, monitorea el progreso y controla el proyecto. Decisión: ¿se requiere control de cambios?",
        responsibleLane: "PMOs",
        type: "decision",
        branches: [
          { label: "SI", text: "Se gestiona la solicitud de cambio.", targetSubStepId: "pr-05" },
          { label: "NO", text: "El flujo continúa directamente hacia la consolidación.", targetSubStepId: "pr-06" },
        ],
      },
      {
        id: "pr-05",
        order: 5,
        title: "Gestión automatizada de solicitudes de cambio",
        description: "Las solicitudes de cambio se manejan a través de un sistema automatizado.",
        responsibleLane: "PMOs",
        type: "approval",
        approverRoleId: "pmo",
        formFields: [
          {
            id: "solicitudesCambio", label: "Solicitudes de cambio", type: "table",
            columns: [
              { id: "titulo", label: "Título", type: "text" },
              { id: "impacto", label: "Impacto", type: "select" },
              { id: "status", label: "Status", type: "select" },
            ],
          },
        ],
        branches: [{ label: "SI", text: "Continúa hacia la consolidación de hitos.", targetSubStepId: "pr-06" }],
      },
      {
        id: "pr-06",
        order: 6,
        title: "Consolidación de Carta de Cierre de Hitos",
        description: "Se reúne y formaliza la documentación necesaria para el cierre de los hitos del proyecto.",
        responsibleLane: "Portafolio / SE / Serv. Est.",
        type: "task",
      },
      {
        id: "pr-07",
        order: 7,
        title: "Revisión de Órdenes (proceso financiero paralelo)",
        description: "De forma paralela, el equipo de finanzas y compras revisa las órdenes de servicio o compra generadas.",
        responsibleLane: "Finanzas TI / Compras",
        type: "task",
        formFields: [
          {
            id: "ordenes", label: "Órdenes de compra/servicio", type: "table",
            columns: [
              { id: "numero", label: "Número", type: "text" },
              { id: "proveedor", label: "Proveedor", type: "text" },
              { id: "monto", label: "Monto", type: "currency" },
              { id: "status", label: "Status", type: "select" },
            ],
          },
        ],
      },
      {
        id: "pr-08",
        order: 8,
        title: "Revisión, aprobación y envío a pago de Órdenes",
        description: "Tras la revisión, se aprueban las órdenes y se envían para su correspondiente pago.",
        responsibleLane: "Finanzas TI / Compras",
        type: "approval",
        approverRoleId: "director-finanzas",
      },
      {
        id: "pr-09",
        order: 9,
        title: "Cierre de Hitos",
        description: "Con la documentación consolidada, se procede al cierre formal de los hitos.",
        responsibleLane: "Portafolio / SE / Serv. Est.",
        type: "task",
      },
      {
        id: "pr-10",
        order: 10,
        title: "Actualizar Plan de Trabajo & Notificación",
        description: "Se actualiza el plan de trabajo para reflejar los avances y se notifica a todos los interesados.",
        responsibleLane: "PMOs",
        type: "task",
      },
    ],
  },

  {
    id: "cierre-proyecto",
    order: 5,
    key: "flujo-5",
    name: "Cierre de Proyecto",
    shortName: "Cierre",
    sourceFlow: "Flujo 5 - Flujo Homologado To Be - Cierre de proyecto",
    description:
      "Cierre de actividades, validación de pagos al 100%, cierre/capitalización del PEP y evaluación anual del proyecto.",
    lanes: ["PMOs", "Portafolio / Serv. Est.", "Líderes Técnicos", "Finanzas TI / SE Finanzas"],
    color: "#323338",
    substeps: [
      {
        id: "c-01",
        order: 1,
        title: "Cierre de Actividades y Elaboración Carta Cierre",
        description: "La PMO cierra formalmente las actividades del proyecto y elabora la Carta de Cierre.",
        responsibleLane: "PMOs",
        type: "task",
        formFields: [{ id: "cartaCierre", label: "Carta de cierre", type: "file" }],
      },
      {
        id: "c-02",
        order: 2,
        title: "Revisión y Gestión de Pagos",
        description: "El equipo de Portafolio inicia la revisión y gestión final de los pagos pendientes.",
        responsibleLane: "Portafolio / Serv. Est.",
        type: "task",
      },
      {
        id: "c-03",
        order: 3,
        title: "Cierre de Pagos",
        description: "Finanzas ejecuta el cierre de todos los pagos relacionados con el proyecto.",
        responsibleLane: "Finanzas TI / SE Finanzas",
        type: "task",
      },
      {
        id: "c-04",
        order: 4,
        title: "Resumen Financiero",
        description: "Se elabora un resumen financiero final del proyecto.",
        responsibleLane: "Finanzas TI / SE Finanzas",
        type: "task",
        formFields: [
          { id: "montoEjecutado", label: "Monto ejecutado", type: "currency" },
          { id: "montoPresupuestado", label: "Monto presupuestado", type: "currency" },
          { id: "variacion", label: "Variación (%)", type: "number" },
        ],
      },
      {
        id: "c-05",
        order: 5,
        title: "¿Pagos al 100%?",
        description: "Los Líderes Técnicos validan si los pagos están al 100%.",
        responsibleLane: "Líderes Técnicos",
        type: "approval",
        approverRoleId: "lideres-tecnicos",
        branches: [
          { label: "NO", text: "Se regresa a Revisión y Gestión de Pagos para resolver discrepancias.", targetSubStepId: "c-02" },
          { label: "SI", text: "El flujo de cierre puede continuar.", targetSubStepId: "c-06" },
        ],
      },
      {
        id: "c-06",
        order: 6,
        title: "Envío versión final de Cierre",
        description: "Se envía la versión final de la documentación de cierre.",
        responsibleLane: "Portafolio / Serv. Est.",
        type: "task",
      },
      {
        id: "c-07",
        order: 7,
        title: "Recolección y validación",
        description: "Se recolecta y valida toda la información y documentación para asegurar que el cierre sea completo.",
        responsibleLane: "Portafolio / Serv. Est.",
        type: "task",
      },
      {
        id: "c-08",
        order: 8,
        title: "Solicitud Cierre/Baja de PEP & Integración",
        description: "Se solicita formalmente el cierre o la baja del Elemento PEP y se integra la información final.",
        responsibleLane: "Portafolio / Serv. Est.",
        type: "task",
        formFields: [{ id: "numeroPEP", label: "Número de PEP", type: "text" }],
      },
      {
        id: "c-09",
        order: 9,
        title: "Capitalización PEP",
        description: "Finanzas procede con la capitalización del PEP, paso contable clave para el cierre financiero.",
        responsibleLane: "Finanzas TI / SE Finanzas",
        type: "approval",
        approverRoleId: "director-finanzas",
      },
      {
        id: "c-10",
        order: 10,
        title: "Formalización y entrega",
        description: "Se formaliza el cierre total del proyecto y se realiza la entrega final.",
        responsibleLane: "Portafolio / Serv. Est.",
        type: "task",
      },
      {
        id: "c-11",
        order: 11,
        title: "Evaluación Anual de Proyectos y Publicación",
        description: "El proyecto es incluido en la evaluación anual y sus resultados son publicados.",
        responsibleLane: "PMOs",
        type: "task",
        formFields: [
          {
            id: "calificacion", label: "Calificación", type: "select",
            options: [1, 2, 3, 4, 5].map((n) => ({ value: String(n), label: `${n}` })),
          },
          { id: "publicar", label: "Publicar resultados", type: "toggle" },
        ],
      },
    ],
  },
];

export const stageById = (id: string): Stage | undefined =>
  stages.find((stage) => stage.id === id);

export const subStepById = (stageId: string, subStepId: string) =>
  stageById(stageId)?.substeps.find((s) => s.id === subStepId);
