import { Project } from "./types";

/**
 * Portafolio dummy: proyectos distribuidos en las distintas etapas y estados,
 * usados únicamente para el maquetado (sin persistencia real).
 */
export const projects: Project[] = [
  {
    id: "proj-01",
    name: "App Móvil de Autoservicio",
    description: "Nueva app móvil para que los clientes gestionen su cuenta sin pasar por sucursal.",
    area: "Banca Digital",
    owner: "Mariana Solís",
    priority: "Alta",
    status: "En proceso",
    currentStageId: "priorizacion",
    currentSubStepId: "p-06",
    budgetEstimate: 4200000,
    startDate: "2026-07-01",
    targetDate: "2027-02-15",
    documents: [
      {
        id: "doc-01",
        name: "Business-Case-Autoservicio.pdf",
        size: 842_312,
        type: "application/pdf",
        uploadedAt: "2026-07-10T15:00:00.000Z",
        aiInsight: "Detecté que este documento es un Business Case. Sugerencia: usa sus cifras de ROI para completar el campo 'Beneficios esperados' del Canvas.",
      },
    ],
    approvals: [],
    stageData: {
      priorizacion: {
        titulo: "App Móvil de Autoservicio",
        areaSolicitante: "Banca Digital",
        esTI: "si",
        prioridad: "alta",
        objetivo: "Reducir el volumen de trámites en sucursal migrándolos a la app móvil.",
      },
    },
  },
  {
    id: "proj-02",
    name: "Plataforma de Onboarding Digital",
    description: "Alta de clientes 100% digital con validación biométrica.",
    area: "Experiencia de Cliente",
    owner: "Rodrigo Peña",
    priority: "Media",
    status: "Por iniciar",
    currentStageId: "priorizacion",
    currentSubStepId: "p-01",
    budgetEstimate: 2800000,
    startDate: "2026-09-01",
    targetDate: "2027-04-30",
    documents: [],
    approvals: [],
    stageData: {},
  },
  {
    id: "proj-03",
    name: "Rediseño Portal de Clientes",
    description: "Modernización del portal web transaccional de clientes.",
    area: "Banca Digital",
    owner: "Ana Castillo",
    priority: "Alta",
    status: "En proceso",
    currentStageId: "estimacion-preliminar",
    currentSubStepId: "e-04",
    budgetEstimate: 6500000,
    startDate: "2026-05-12",
    targetDate: "2027-01-31",
    documents: [
      {
        id: "doc-02",
        name: "Diagnostico-UX-Portal.pdf",
        size: 1_204_558,
        type: "application/pdf",
        uploadedAt: "2026-05-20T12:30:00.000Z",
        aiInsight: "El documento incluye hallazgos de usabilidad; considera adjuntarlos como referencia en 'Sistemas impactados'.",
      },
    ],
    approvals: [
      {
        id: "appr-01",
        projectId: "proj-03",
        stageId: "priorizacion",
        subStepId: "p-07",
        roleId: "bp",
        userId: "u-05",
        decision: "aprobado",
        comment: "Canvas completo y con buena justificación de negocio.",
        ts: "2026-05-25T09:15:00.000Z",
      },
    ],
    stageData: {
      "estimacion-preliminar": {
        sistemasImpactados: ["portal-web", "crm"],
        complejidad: "alta",
        horasInfraestructura: 320,
        horasDesarrollo: 980,
        horasUX: 240,
        horasQA: 300,
        costoEstimado: 6500000,
      },
    },
  },
  {
    id: "proj-04",
    name: "Integración de Pagos con Wallets",
    description: "Soporte para pagos con wallets digitales (Apple Pay / Google Pay) en el checkout.",
    area: "Medios de Pago",
    owner: "Luis Fernández",
    priority: "Alta",
    status: "Atrasado",
    currentStageId: "estimacion-preliminar",
    currentSubStepId: "e-02",
    budgetEstimate: 3100000,
    startDate: "2026-04-01",
    targetDate: "2026-10-15",
    documents: [],
    approvals: [],
    stageData: {
      "estimacion-preliminar": {
        sistemasImpactados: ["core", "app-movil"],
        complejidad: "media",
      },
    },
  },
  {
    id: "proj-05",
    name: "Automatización de Cobranza",
    description: "Motor de reglas para automatizar recordatorios y gestiones de cobranza temprana.",
    area: "Riesgos",
    owner: "Diego Ramos",
    priority: "Media",
    status: "En proceso",
    currentStageId: "autorizacion",
    currentSubStepId: "a-01",
    budgetEstimate: 5400000,
    startDate: "2026-06-01",
    targetDate: "2027-03-01",
    documents: [],
    approvals: [
      {
        id: "appr-02",
        projectId: "proj-05",
        stageId: "estimacion-preliminar",
        subStepId: "e-08",
        roleId: "bp",
        userId: "u-06",
        decision: "aprobado",
        ts: "2026-06-10T10:00:00.000Z",
      },
    ],
    stageData: {
      autorizacion: {
        resumenEjecutivo: "Automatizar el 60% de las gestiones de cobranza temprana reduciendo costo operativo.",
        roiEstimado: 34,
        montoSolicitado: 5400000,
      },
    },
  },
  {
    id: "proj-06",
    name: "Chatbot de Soporte Interno",
    description: "Asistente conversacional para resolver dudas frecuentes de colaboradores (RH, TI, Finanzas).",
    area: "Servicios Compartidos",
    owner: "Paola Ibarra",
    priority: "Baja",
    status: "Por iniciar",
    currentStageId: "autorizacion",
    currentSubStepId: "a-01",
    budgetEstimate: 1900000,
    startDate: "2026-09-15",
    targetDate: "2027-01-15",
    documents: [],
    approvals: [],
    stageData: {},
  },
  {
    id: "proj-07",
    name: "Rediseño CRM Ventas",
    description: "Rediseño del CRM comercial para unificar la vista 360 del cliente.",
    area: "Comercial",
    owner: "Karla Nájera",
    priority: "Alta",
    status: "En proceso",
    currentStageId: "formalizacion-autorizacion",
    currentSubStepId: "fa-12",
    budgetEstimate: 8900000,
    pepNumber: "PEP-2026-0142",
    startDate: "2026-03-01",
    targetDate: "2027-05-30",
    documents: [],
    approvals: [
      {
        id: "appr-03",
        projectId: "proj-07",
        stageId: "formalizacion-autorizacion",
        subStepId: "fa-01",
        roleId: "direccion-general",
        userId: "u-13",
        decision: "aprobado",
        comment: "Aprobado por impacto directo en meta comercial anual.",
        ts: "2026-03-20T11:00:00.000Z",
      },
      {
        id: "appr-04",
        projectId: "proj-07",
        stageId: "formalizacion-autorizacion",
        subStepId: "fa-09",
        roleId: "director-finanzas",
        userId: "u-16",
        decision: "aprobado",
        ts: "2026-04-02T09:40:00.000Z",
      },
    ],
    stageData: {
      "formalizacion-autorizacion": {
        proveedores: [{ proveedor: "Salesforce MX", contrato: "CT-8891", status: "en-negociacion" }],
      },
    },
  },
  {
    id: "proj-08",
    name: "Migración Core Bancario",
    description: "Migración del core transaccional a la nueva plataforma cloud-native.",
    area: "Tecnología Core",
    owner: "Jorge Villaseñor",
    priority: "Alta",
    status: "Atrasado",
    currentStageId: "proyecto",
    currentSubStepId: "pr-04",
    budgetEstimate: 42_000_000,
    pepNumber: "PEP-2026-0098",
    startDate: "2025-11-01",
    targetDate: "2027-06-30",
    documents: [],
    approvals: [
      {
        id: "appr-05",
        projectId: "proj-08",
        stageId: "proyecto",
        subStepId: "pr-03",
        roleId: "lideres-tecnicos",
        userId: "u-09",
        decision: "aprobado",
        ts: "2026-06-01T08:00:00.000Z",
      },
    ],
    stageData: {
      proyecto: {
        planAdjunto: "Plan-Migracion-Core-v3.mpp",
        metodologia: "cascada",
        avancePorcentaje: 48,
      },
    },
  },
  {
    id: "proj-09",
    name: "Optimización de Data Warehouse",
    description: "Reestructura de modelos y cargas del DWH corporativo para mejorar tiempos de reporte.",
    area: "Datos y Analítica",
    owner: "Fernanda Ochoa",
    priority: "Media",
    status: "En proceso",
    currentStageId: "proyecto",
    currentSubStepId: "pr-07",
    budgetEstimate: 7_200_000,
    pepNumber: "PEP-2026-0110",
    startDate: "2026-02-01",
    targetDate: "2026-12-15",
    documents: [],
    approvals: [],
    stageData: {
      proyecto: {
        metodologia: "agil",
        avancePorcentaje: 72,
        ordenes: [{ numero: "OC-4521", proveedor: "DataBricks", monto: 980000, status: "en-revision" }],
      },
    },
  },
  {
    id: "proj-10",
    name: "Renovación de Infraestructura Cloud",
    description: "Migración de cargas on-premise restantes a GCP y optimización de costos.",
    area: "Infraestructura",
    owner: "Iván Cordero",
    priority: "Alta",
    status: "En proceso",
    currentStageId: "proyecto",
    currentSubStepId: "pr-02",
    budgetEstimate: 15_600_000,
    pepNumber: "PEP-2026-0087",
    startDate: "2026-01-15",
    targetDate: "2026-11-30",
    documents: [],
    approvals: [],
    stageData: {
      proyecto: { metodologia: "cascada", avancePorcentaje: 30 },
    },
  },
  {
    id: "proj-11",
    name: "Dashboard Financiero Ejecutivo",
    description: "Tablero unificado de indicadores financieros para el comité de dirección.",
    area: "Finanzas",
    owner: "Gabriela Treviño",
    priority: "Media",
    status: "En proceso",
    currentStageId: "cierre-proyecto",
    currentSubStepId: "c-04",
    budgetEstimate: 2_300_000,
    pepNumber: "PEP-2025-0221",
    startDate: "2025-08-01",
    targetDate: "2026-09-30",
    documents: [],
    approvals: [
      {
        id: "appr-06",
        projectId: "proj-11",
        stageId: "proyecto",
        subStepId: "pr-08",
        roleId: "director-finanzas",
        userId: "u-17",
        decision: "aprobado",
        ts: "2026-08-15T13:00:00.000Z",
      },
    ],
    stageData: {
      "cierre-proyecto": {
        montoEjecutado: 2_180_000,
        montoPresupuestado: 2_300_000,
        variacion: -5.2,
      },
    },
  },
  {
    id: "proj-12",
    name: "Portal de Proveedores",
    description: "Autoservicio para que proveedores consulten estatus de pago y suban facturas.",
    area: "Compras",
    owner: "Sofía Elizondo",
    priority: "Baja",
    status: "Finalizado",
    currentStageId: "cierre-proyecto",
    currentSubStepId: "c-11",
    budgetEstimate: 1_750_000,
    pepNumber: "PEP-2025-0176",
    startDate: "2025-05-01",
    targetDate: "2026-06-30",
    documents: [],
    approvals: [
      {
        id: "appr-07",
        projectId: "proj-12",
        stageId: "cierre-proyecto",
        subStepId: "c-05",
        roleId: "lideres-tecnicos",
        userId: "u-11",
        decision: "aprobado",
        comment: "Pagos conciliados al 100%.",
        ts: "2026-06-10T16:00:00.000Z",
      },
      {
        id: "appr-08",
        projectId: "proj-12",
        stageId: "cierre-proyecto",
        subStepId: "c-09",
        roleId: "director-finanzas",
        userId: "u-16",
        decision: "aprobado",
        ts: "2026-06-18T10:00:00.000Z",
      },
    ],
    stageData: {
      "cierre-proyecto": { calificacion: "5", publicar: true },
    },
  },
];

export const projectById = (id: string): Project | undefined =>
  projects.find((project) => project.id === id);
